import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const neueRegrade = localFont({
  src: "./fonts/neue-regrade-variable.ttf",
  display: "swap",
  variable: "--font-neue-regrade",
});

const generalSans = localFont({
  src: "./fonts/GeneralSans-Variable.woff2",
  display: "swap",
  variable: "--font-general-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neueRegrade.variable} ${generalSans.variable}  paragraph text-humble-black bg-pure-white relative flex flex-col overflow-x-hidden`}
      >
        {/* Navbar */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
